events {}

http {
  upstream kafka_ui {
    server kafka-ui:8080;
  }

  upstream grafana {
    server grafana:3000;
  }

  upstream prometheus {
    server prometheus:9090;
  }

#   upstream django {
#     server web:8000;
#   }

  server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certs/localhost.pem;
    ssl_certificate_key /etc/nginx/certs/localhost-key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    location /kafka/ {
      proxy_pass http://kafka_ui/;
    }

    location /grafana/ {
      proxy_pass http://grafana/;
    }

    location /prometheus/ {
      proxy_pass http://prometheus/;
    }

    # location /api/ {
    #   proxy_pass http://django;
    # }
  }

  server {
    listen 80;
    server_name localhost;

    location / {
      return 301 https://$host$request_uri;
    }
  }
}